version: '3'

services:
  # 用来运行 gocqhttp 二进制，注意这里目录是挂载的
  gocqhttp:
    container_name: gocqhttp
    environment:
      - TZ=Asia/Singapore
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./go-cqhttp:/usr/src/app:delegated
    build:
      context: ./go-cqhttp

  # nonebot/quart
  meow:
    container_name: meow
    environment:
      - TZ=Asia/Singapore
      - DATABASE_URI=postgresql://root:password@postgres:5432/meow
    ports:
      - 8080:8080
    depends_on:
      - postgres
    build:
      context: ./meow

  # dev 数据库
  postgres:
    container_name: postgres
    environment:
      - TZ=Asia/Singapore
      - PGTZ=Asia/Singapore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meow
    image: postgres:12.18-alpine

networks:
  default:
    name: meowbot-default